receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 100

exporters:
  otlphttp/trace_exporter:
    endpoint: "http://host.docker.internal:5265/open-telemetry" # replace with https://api.logbee.net/open-telemetry
    compression: none

  otlphttp/log_exporter:
    endpoint: "http://host.docker.internal:5265/open-telemetry" # replace with https://api.logbee.net/open-telemetry
    compression: none
    
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/trace_exporter, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/log_exporter, debug]
